data:
  train_data_path: data/train/mnist_train.csv
  test_data_path: data/test/mnist_test.csv
  pred_data_path: data/prediction.csv

model:
  model_path: mnist/models/model.pth
  in_channels: 1
  out_channels: 10
preprocessing:
  n1: 0.1307
  n2: 0.3081
training:
  batch_size: 32
  shuffle: True
  num_workers: 2
  epochs: 3
  learning_rate: 1e-3
  momentum: 0.9
  nesterov: False
  weight_decay: 5e-4
infer:
  batch_size: 32
  shuffle: False
  num_workers: 2
